spring.application.name=hubspot.api

# Configurações do OAuth com HubSpot
hubspot.client-id=0ef82a76-3095-414d-837c-715d40c7683b
hubspot.client-secret=81acdd4f-0d61-4f78-bcac-494b084069c5
hubspot.redirect-uri=https://api.meetime.redirect
hubspot.scope=crm.objects.contacts.write%20oauth%20crm.objects.contacts.read
hubspot.auth-base-url=https://app.hubspot.com/oauth/authorize
hubspot.token-url=https://api.hubapi.com/oauth/v1/token
hubspot.api-url=api.meetime

secret.key=HmacSHA256
